linters:
    enable-all: true
    disable:
        - funlen
        - gomnd
        - maligned
        - wsl

        # TODO: fix these
        - whitespace
        - stylecheck
        - bodyclose
        - deadcode
        - dupl
        - errcheck
        - gas
        - gochecknoglobals
        - gochecknoinits
        - gocritic
        - gocyclo
        - gocognit
        - gofmt
        - goimports
        - golint
        - lll
        - megacheck
        - varcheck
        - godox

linters-settings:
    golint:
        min-confidence: 0.1
