approved = [
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "mpl-2.0",
]

ignored = [
    "github.com/ghodss/yaml",

    "github.com/inconshreveable/mousetrap", # Apache 2.0
    "github.com/magiconair/properties", # BSD-3
    "github.com/Masterminds/semver", # MIT
    "github.com/Masterminds/sprig", # MIT
    "github.com/davecgh/go-spew", # ISC license
    "github.com/gogo/protobuf", # BSD

    # Vanity URLS :\
    "google.golang.org/grpc",
    "google.golang.org/genproto",
    "cloud.google.com/go",
    "google.golang.org/api",
    "sigs.k8s.io/yaml",
    "go.opencensus.io",

    # Backyards deps
    "gomodules.xyz/jsonpatch/v2", # Apache 2.0
    "gopkg.in/fsnotify.v1", # BSD 3-Clause
    "istio.io/operator", # Apache 2
    "istio.io/pkg", # Apache 2
    "go.uber.org/atomic", # MIT
    "go.uber.org/multierr", # MIT
    "go.uber.org/zap", # MIT
    "emperror.dev/handler/logrus", # MIT
    "emperror.dev/errors", # MIT
]
